core/urls.py
from django.urls import path
from .views import inicio, registrarme, nosotros
from .views import usuarios,ingresar, usuarios
from .views import misdatos,salir
from .views import poblar
from .views import premio
from .views import mipassword, cambiar_password
from . import views


urlpatterns = [
    path('', inicio, name='inicio'),
    path('inicio', inicio, name='inicio'),
    path('registrarme', registrarme, name='registrarme'),
    path('nosotros', nosotros, name='nosotros'),
    path('usuarios/<accion>/<id>', usuarios, name='usuarios'),
    path('cambiar_password', cambiar_password, name='cambiar_password'),
    path('ingresar', ingresar, name='ingresar'),
    path('misdatos', misdatos, name='misdatos'),
    path('mipassword', mipassword, name='mipassword'),
    path('salir', salir, name='salir'),
    path('premio', premio, name='premio'),
    path('poblar', poblar, name='poblar'),
    path('reservar/', views.reserva_cita, name='reservar_cita'),
    path('reservas/', views.ver_reservas, name='reservas'),
    path('editar-cita/<int:cita_id>/', views.editar_cita, name='editar_cita'),
    path('anular-cita/<int:cita_id>/', views.anular_cita, name='anular_cita'),
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    #path('api/', include('apirest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from core.templatetags.custom_filters import formatear_dinero
from django.db import models
from django.db.models import Min
from django.db import connection

class Especialidad(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Medico(models.Model):
    nombre = models.CharField(max_length=100)
    especialidad = models.ForeignKey(Especialidad, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre} - {self.especialidad.nombre}"


class Cita(models.Model):
    TIPO_DOCUMENTO_CHOICES = [
        ('DNI', 'DNI'),
        ('PASAPORTE', 'Pasaporte'),
        ('CEDULA', 'Cédula de Identidad'),
    ]
    
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    medico = models.CharField(max_length=100)
    fecha = models.DateField()
    hora = models.TimeField()
    tipo_documento = models.CharField(
        max_length=20,
        choices=TIPO_DOCUMENTO_CHOICES,
        verbose_name='Tipo de documento de identidad',
        default='DNI',
    )
    numero_documento = models.CharField(
        max_length=20, 
        verbose_name='Número de documento', 
        default='123456789'  # Valor predeterminado para numero_documento
    )
    estado = models.CharField(
        max_length=20, 
        choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada')]
    )

    def __str__(self):
        return f"Cita de {self.usuario} con {self.medico} en {self.fecha}"


    
class Perfil(models.Model):
    USUARIO_CHOICES = [
        ('Cliente', 'Cliente'),
        ('Medico', 'Medico'),
        ('Administrador', 'Administrador'),
        ('Superusuario', 'Superusuario'),
    ]
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo_usuario = models.CharField(
        choices=USUARIO_CHOICES,
        max_length=50,
        blank=False,
        null=False,
        verbose_name='Tipo de usuario'
    )
    rut = models.CharField(max_length=15, blank=False, null=False, verbose_name='RUT')
    direccion = models.CharField(max_length=800, blank=False, null=False, verbose_name='Dirección')
    subscrito = models.BooleanField(default=False)
    imagen = models.ImageField(upload_to='perfiles/', blank=False, null=False, verbose_name='Imagen')
    
    class Meta:
        db_table = 'Perfil'
        verbose_name = "Perfil de usuario"
        verbose_name_plural = "Perfiles de usuarios"
        ordering = ['tipo_usuario']

    def __str__(self):
        subscrito = ''
        if self.tipo_usuario == 'Cliente':
            subscrito = ' subscrito' if self.subscrito else ' no subscrito'
        return f'{self.usuario.first_name} {self.usuario.last_name} (ID {self.id} - {self.tipo_usuario}{subscrito})'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar el Perfil',
            'accion_actualizar': 'actualizar el Perfil'
        }

core/views.py
from datetime import date
from .zpoblar import poblar_bd
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse
from django.utils.safestring import SafeString
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Perfil
from .forms import IngresarForm, UsuarioForm, PerfilForm
from .forms import RegistroUsuarioForm, RegistroPerfilForm
from .tools import eliminar_registro, verificar_eliminar_registro, show_form_errors
from django.core.mail import send_mail
from .forms import ReservaCitaForm, ReporteForm, EditarCitaForm
from .models import Cita, Medico, Especialidad
from django.http import HttpResponse
import csv
from io import StringIO

@login_required
def reserva_cita(request):
    especialidades = Especialidad.objects.all()  # Obtener todas las especialidades
    doctores = Medico.objects.all()  # Obtener todos los doctores

    # Filtrar doctores si ya se ha seleccionado una especialidad
    if 'especialidad' in request.POST:
        especialidad_id = request.POST.get('especialidad')
        doctores = Medico.objects.filter(especialidad_id=especialidad_id)  # Filtrar doctores según especialidad seleccionada

    if request.method == 'POST':
        form = ReservaCitaForm(request.POST)
        
        if form.is_valid():
            especialidad = form.cleaned_data['especialidad']
            doctor = form.cleaned_data['doctor']
            
            # Crear una nueva cita con la información del formulario
            cita = Cita(
                usuario=request.user,  # Usar el usuario autenticado
                medico=doctor,  # Usar el médico seleccionado
                especialidad=especialidad,  # Guardar la especialidad como objeto
                fecha=form.cleaned_data['fecha'],
                hora=form.cleaned_data['hora'],
                tipo_documento=form.cleaned_data['tipo_documento'],
                numero_documento=form.cleaned_data['numero_documento'],
                estado='pendiente'  # Asignamos estado pendiente
            )
            cita.save()  # Guardar la cita en la base de datos

            # Enviar correo de confirmación al usuario
            send_mail(
                'Confirmación de tu cita médica',
                f'Hola {cita.usuario.username},\n\nTu cita médica ha sido reservada para el día {cita.fecha} a las {cita.hora}.',
                'zi.yuan@duocuc.cl',  # Remitente
                [cita.usuario.email],  # Destinatario (usuario)
                fail_silently=False,
            )

            # Enviar un correo al médico con los detalles de la cita
            send_mail(
                'Nueva cita médica reservada',
                f'Se ha reservado una nueva cita médica para {cita.usuario.username} (DNI: {cita.numero_documento}) el día {cita.fecha} a las {cita.hora}.',
                'zi.yuan@duocuc.cl',  # Remitente
                [doctor.email],  # Destinatario (doctor)
                fail_silently=False,
            )

            # Mostrar mensaje de éxito en la interfaz
            messages.success(request, '¡Cita reservada con éxito! Se ha enviado un correo de confirmación.')
            
            return redirect('ver_reservas')  # Redirigir a la página de citas reservadas
        else:
            # Si el formulario no es válido, pasamos los doctores filtrados
            return render(request, 'core/reserva_cita.html', {
                'form': form, 
                'especialidades': especialidades, 
                'doctores': doctores
            })
    else:
        form = ReservaCitaForm()

    return render(request, 'core/reserva_cita.html', {
        'form': form,
        'especialidades': especialidades,
        'doctores': doctores
    })

@login_required
def ver_reservas(request):
    # Si el usuario es superusuario  o administrador puede ver todas las citas
    if request.user.is_superuser or request.user.is_staff:
        citas = Cita.objects.all()  # Mostrar todas las citas si es superusuario o admin
    else:
        # Si no es superusuario o admin solo verá sus propias citas
        citas = Cita.objects.filter(usuario=request.user)

    if request.method == 'POST':
        # Si se recibe un POST para editar una cita
        form = EditarCitaForm(request.POST)
        if form.is_valid():
            cita_id = form.cleaned_data['cita_id']  # Añadimos un campo hidden para el ID de la cita
            cita = get_object_or_404(Cita, id=cita_id)
            cita.fecha = form.cleaned_data['fecha']
            cita.hora = form.cleaned_data['hora']
            cita.save()
            return redirect('ver_reservas')  # Redirige a la misma página después de guardar la cita editada
    else:
        form = EditarCitaForm()

    return render(request, 'core/ver_reservas.html', {'citas': citas, 'form': form})

@login_required
def editar_cita(request, cita_id):
    cita = get_object_or_404(Cita, id=cita_id)
    
    if request.method == 'POST':
        form = EditarCitaForm(request.POST, instance=cita)
        
        if form.is_valid():
            form.save()  # Guardar los cambios en la cita
            return redirect('reservas')  # Redirigir a la página de citas reservadas

    form = EditarCitaForm(instance=cita)
    return render(request, 'core/editar_cita.html', {'form': form, 'cita': cita})

# Eliminar una cita
@login_required
def anular_cita(request, cita_id):
    # Obtener la cita o devolver un error 404 si no existe
    cita = get_object_or_404(Cita, id=cita_id)

    # Verificar que el usuario es el propietario o un superusuario
    if request.user != cita.usuario and not request.user.is_superuser:
        return JsonResponse({'error': 'No tienes permiso para anular esta cita'}, status=403)

    # Eliminar la cita
    cita.delete()
    return JsonResponse({'message': 'Cita eliminada correctamente'}, status=200)

# Actualizar el estado de una cita
def actualizar_estado_cita(request, cita_id):
    if request.method == 'POST':
        cita = Cita.objects.get(id=cita_id)
        data = json.loads(request.body)  # Obtener el nuevo estado desde la solicitud
        cita.estado = data.get('estado')
        cita.save()
        return JsonResponse({'message': f'Estado actualizado a {cita.estado}'}, status=200)


@login_required
def generar_informe(request):
    if request.method == 'POST':
        form = ReporteForm(request.POST)
        if form.is_valid():
            medico = form.cleaned_data['medico']
            fecha_inicio = form.cleaned_data['fecha_inicio']
            fecha_fin = form.cleaned_data['fecha_fin']
            citas = Cita.objects.filter(fecha__range=[fecha_inicio, fecha_fin])
            if medico:
                citas = citas.filter(medico=medico)

            # Generar CSV
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="reporte_citas.csv"'
            writer = csv.writer(response)
            writer.writerow(['Usuario', 'Medico', 'Fecha', 'Hora', 'Estado'])
            for cita in citas:
                writer.writerow([cita.usuario.username, cita.medico.nombre, cita.fecha, cita.hora, cita.estado])

            return response
    else:
        form = ReporteForm()
    return render(request, 'generar_informe.html', {'form': form})


# Se usará el decorador "@user_passes_test" para realizar la autorización básica a las páginas.
# De este modo sólo entrarán a las páginas las personas que sean del tipo_usuario permitido.
# Si un usuario no autorizado intenta entrar a la página, será redirigido al inicio o a ingreso

# Revisar si el usuario es personal de la empresa (staff administrador o superusuario) autenticado y con cuenta activa
def es_personal_autenticado_y_activo(user):
    return (user.is_staff or user.is_superuser) and user.is_authenticated and user.is_active

# Revisar si el usuario no está autenticado, es decir, si aún está navegando como usuario anónimo
def es_usuario_anonimo(user):
    return user.is_anonymous

# Revisar si el usuario es un cliente (no es personal de la empresa) autenticado y con cuenta activa
def es_cliente_autenticado_y_activo(user):
    return (not user.is_staff and not user.is_superuser) and user.is_authenticated and user.is_active

def inicio(request):
    return render(request, 'core/inicio.html')

def nosotros(request):
    return render(request, 'core/nosotros.html')

def premio(request):
    return render(request, 'core/api.html')

@user_passes_test(es_usuario_anonimo, login_url='inicio')
def ingresar(request):
    if request.method == "POST":
        form = IngresarForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if request.POST.get('recordar_cuenta'):
                        # Si el checkbox está marcado, establecer la cookie para recordar la sesión
                        request.session.set_expiry(1209600)  # 2 semanas en segundos
                    messages.success(request, f'¡Bienvenido(a) {user.first_name} {user.last_name}!')
                    return redirect(inicio)
                else:
                    messages.error(request, 'La cuenta está desactivada.')
            else:
                messages.error(request, 'La cuenta o la contraseña no son correctos.')
        else:
            messages.error(request, 'No se pudo ingresar al sistema.')
            show_form_errors(request, [form])

    else:  # Método GET
        form = IngresarForm()

    context = {

core/templates/core/ingresar.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
<div class="login-body">
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-sm-12 col-md-6">
        <div class="card border-0 shadow-lg">
          <div class="card-body">
            <h2 class="text-center mb-4">Iniciar sesión</h2>
            <form id="form-ingreso" method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
              {% csrf_token %}
              
              <div class="form-group">
                <label for="id_username" class="d-block">Usuario:</label>
                {{ form.username|add_class:"form-control" }}
                <div class="invalid-feedback">
                  {% for error in form.username.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              </div>
  
              <div class="form-group">
                <label for="id_password" class="d-block">Contraseña:</label>
                {{ form.password|add_class:"form-control" }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              </div>
  
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="recordar_cuenta" name="recordar_cuenta">
                <label class="form-check-label" for="recordar_cuenta">Recordar cuenta</label>
              </div>
  
              <div class="text-center mt-4">
                <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
              </div>
  
              <p class="text-center mt-3">
                ¿No tienes cuenta? <a href="{% url 'registrarme' %}">Registrarme</a>
              </p>
            </form>

            <!-- <form method="POST" action="{% url 'poblar' %}">
              {% csrf_token %}
              <div class="d-flex justify-content-center">
                  <button type="submit" class="btn btn-primary">Poblar la Base de Datos</button>
              </div>
            </form> -->
          
          </div>
        </div>

        {% include 'common/combobox_usuarios.html' %}

        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block script %}
  <script src="{% static 'core/js/ingresar.js' %}"></script>
  <link rel="stylesheet" href="{% static 'core/css/login.css' %}"/>
{% endblock script %}

core/templates/core/registrarme.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_filters %}
{% load form_tags %}

{% block content %}
<div class="registro-body">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="text-center">Registro de Clientes</h2>
          <form id="form-registrarme" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <ul class="form-list">
              <div class="form-group">
                {{ form_usuario.username.label_tag }} {{ form_usuario.username|add_class:"form-control" }}
              </div>
              <div class="form-group">
                {{ form_perfil.rut.label_tag }}{{ form_perfil.rut|add_class:"form-control" }}
              </div>
              <div class="form-group">
                {{ form_usuario.first_name.label_tag }} {{ form_usuario.first_name|add_class:"form-control" }}
              </div>
              <div class="form-group">
                {{ form_usuario.last_name.label_tag }} {{ form_usuario.last_name|add_class:"form-control" }}
              </div>
              <div class="form-group">
                {{ form_usuario.email.label_tag }} {{ form_usuario.email|add_class:"form-control" }}
              </div>
              <div class="form-group">
                {{ form_perfil.direccion.label_tag }} {{ form_perfil.direccion|add_class:"form-control" }}
              </div>
              <div class="form-group form-check">
                {{ form_perfil.subscrito|add_class:"form-check-input" }} {{ form_perfil.subscrito.label_tag|add_class:"form-check-label" }}
                <span class="extra-text">¿Quiere suscribirse por un aporte mensual de $3000 y obtener 5% en sus compras?</span>
              </div>
              <div class="form-group">
                {{ form_perfil.imagen.label_tag }} <input type="file" id="id_imagen" name="imagen" class="form-control">
              </div>
              <div class="form-group">
                {{ form_usuario.password1.label_tag }} {{ form_usuario.password1|add_class:"form-control" }}
              </div>
              <div class="form-group">
                {{ form_usuario.password2.label_tag }} {{ form_usuario.password2|add_class:"form-control" }}
              </div>
            </ul>
            <br>
            <p class="text-center">
              ¿Ya tienes cuenta?
              <a href="{% url 'ingresar' %}">Iniciar Sesión</a>
            </p>
            <div class="mt-2 mb-3 text-center">
              <button type="submit" class="btn btn-primary btn-block">Registrarme</button>
              <button type="reset" class="btn btn-warning btn-block" id="limpiar_formulario">Limpiar</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- Cuadro de vista previa de imagen -->
    <div class="col-sm-12 col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title text-center">Foto del usuario</h4>
          <img id="preview-image" src="{% static 'core/img/sin-imagen.png' %}" alt="Vista previa de la imagen" class="img-fluid img-thumbnail" style="max-width: 100%; height: auto;">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'core/js/registrarme.js' %}"></script>
<link rel="stylesheet" href="{% static 'core/css/register.css' %}">
<script>
document.getElementById('id_imagen').onchange = function (evt) {
  const [file] = this.files;
  if (file) {
    document.getElementById('preview-image').src = URL.createObjectURL(file);
  }
};
</script>
{% endblock script %}

core/templates/core/reserva_cita.html
{% extends 'core/base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-start vh-100" style="margin-top: 50px;">
  <div class="card p-4 shadow-lg" style="background-color: rgba(128, 128, 128, 0.7); border-radius: 15px; width: 50%;">
    <h1 class="text-center mb-4 text-white">Reserva tu cita médica</h1>

    <form method="POST" action="{% url 'reservar_cita' %}">
      {% csrf_token %}
      <div class="row">
        <!-- Selección de especialidad -->
        <div class="col-md-6 mb-3">
          <label for="especialidad" class="form-label text-white">Especialidad</label>
          <select class="form-select" id="especialidad" name="especialidad" required>
            <option value="" selected disabled>Selecciona una especialidad</option>
            {% for especialidad in especialidades %}
              <option value="{{ especialidad.id }}" data-doctor="{{ especialidad.medico_set.first.id }}" data-doctor-name="{{ especialidad.medico_set.first.nombre }}">
                {{ especialidad.nombre }}
              </option>
            {% endfor %}
          </select>
        </div>

        <!-- Campo de doctor (solo lectura) -->
        <div class="col-md-6 mb-3">
          <label for="doctor" class="form-label text-white">Doctor</label>
          <input type="text" class="form-control" id="doctor" name="doctor" readonly>
        </div>
      </div>

      <!-- Selección de fecha y hora -->
      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="fecha" class="form-label text-white">Fecha</label>
          <input type="date" class="form-control" id="fecha" name="fecha" required>
        </div>

        <div class="col-md-6 mb-3">
          <label for="hora" class="form-label text-white">Hora</label>
          <input type="time" class="form-control" id="hora" name="hora" required>
        </div>
      </div>

      <!-- Información adicional -->
      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="tipo_documento" class="form-label text-white">Tipo de documento</label>
          <select class="form-select" id="tipo_documento" name="tipo_documento" required>
            <option value="" selected disabled>Selecciona un tipo de documento</option>
            <option value="DNI">DNI</option>
            <option value="Pasaporte">Pasaporte</option>
          </select>
        </div>

        <div class="col-md-6 mb-3">
          <label for="numero_documento" class="form-label text-white">Número de documento</label>
          <input type="text" class="form-control" id="numero_documento" name="numero_documento" required>
        </div>
      </div>

      <!-- Botón de envío -->
      <div class="text-center">
        <button type="submit" class="btn btn-light mt-3">Reservar cita</button>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

{% block script %}
<script>
  // JavaScript para actualizar el campo 'doctor' automáticamente al seleccionar la especialidad
  document.getElementById('especialidad').addEventListener('change', function () {
    var especialidadId = this.value;
    var doctorField = document.getElementById('doctor');

    // Obtener el nombre del médico basado en la especialidad seleccionada
    var selectedOption = this.selectedOptions[0];
    var doctorName = selectedOption.getAttribute('data-doctor-name');

    // Asignar el nombre del médico al campo de doctor
    if (doctorName) {
      doctorField.value = doctorName; // Asigna el nombre del médico
    }
  });
</script>

<script>
  document.getElementById('especialidad').addEventListener('change', function () {
    var especialidadId = this.value;
    var doctorSelect = document.getElementById('doctor');
    var doctorIdField = document.getElementById('doctor_id'); // Campo oculto para el ID del doctor

    // Limpiar la lista de doctores y el valor del campo oculto
    doctorSelect.innerHTML = '<option value="" selected disabled>Selecciona un doctor</option>';
    doctorIdField.value = '';  // Limpiar el campo oculto del ID del doctor

    if (especialidadId) {
        fetch(`/api/doctores/${especialidadId}/`)  // Se asume que esta ruta devuelve la lista de doctores de la especialidad
            .then(response => response.json())
            .then(data => {
                data.doctores.forEach(function (doctor) {
                    var option = document.createElement('option');
                    option.value = doctor.id;
                    option.textContent = doctor.nombre;
                    doctorSelect.appendChild(option);
                });
            })
            .catch(error => console.error('Error al cargar doctores:', error));
    }
});

// Al seleccionar un doctor, actualizar el campo oculto con el ID del doctor
document.getElementById('doctor').addEventListener('change', function () {
    var doctorId = this.value;
    var doctorIdField = document.getElementById('doctor_id');
    doctorIdField.value = doctorId;  // Asigna el ID del doctor al campo oculto
});

</script>



{% endblock script%}

core/templates/core/usuarios.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
<div class="container">
  <div class="col-12 col-md-12 col-lg-10 mx-auto"> <!-- Ajustamos los tamaños de las columnas para centrar y limitar el ancho -->
    <div class="card border-0 shadow-lg">
      <div class="card-body">
        <h2 class="card-title text-center mb-4">Gestion de Usuarios</h2>
        <form id="form-usuarios" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                {{ form_usuario|as_bootstrap_form }}
                {{ form_perfil|as_bootstrap_form }}
              </div>
              <input type="file" id="id_imagen" name="imagen" style="display: none;">
              <div class="text-center">
                <button type="submit" class="btn btn-primary btn-md">Guardar</button>
                <a href="{% url 'usuarios' 'crear' '0' %}" class="btn btn-primary btn-md">Nuevo</a>
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3 text-center">
                <h4 class="mb-3">Imagen del Usuario</h4>
                {% if form_perfil.imagen.value %}
                  <img id="cuadro-imagen" src="/media/{{ form_perfil.imagen.value }}" class="img-thumbnail me-3" style="max-width: 250px; height: auto; object-fit: cover;">
                {% else %}
                  <img id="cuadro-imagen" src="{% static 'core/img/sin-imagen.png' %}" class="img-thumbnail me-3" style="max-width: 250px; height: auto; object-fit: cover;">
                {% endif %}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12"> <!-- Se elimina el tamaño de columna limitado -->
      <div class="card border-0 shadow-lg card-usuarios-registrados"> <!-- Se aplica la nueva clase -->
        <div class="card-body">
          <h2 class="text-center mb-4">Usuarios Registrados</h2>
          <div class="table-responsive">
            <table id="tabla-principal" class="table table-hover text-center">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Cuenta</th>
                  <th>Tipo usuario</th>
                  <th>Nombre</th>
                  <th>Apellidos</th>
                  <th>Correo</th>
                  <th>RUT</th>
                  <th>Imagen</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                {% for usuario in usuarios %}
                <tr>
                  <td>{{usuario.id}}</td>
                  <td>{{usuario.username }}</td>
                  <td>{{usuario.perfil.tipo_usuario}}</td>
                  <td>{{usuario.first_name}}</td>
                  <td>{{usuario.last_name }}</td>
                  <td>{{usuario.email }}</td>
                  <td>{{usuario.perfil.rut}}</td>
                  <td>
                    {% if usuario.perfil.imagen %}
                      <img src="/media/{{ usuario.perfil.imagen }}" class="usuario-sm img-fluid" style="max-width: 100px;" alt="">
                    {% else %}
                      <img src="{% static 'core/img/sin-imagen.png' %}" class="usuario-sm img-fluid" style="max-width: 100px;" alt="Sin imagen">
                    {% endif %}
                  </td>
                  <td>
                    <div class="btn-group">
                      <a href="{% url 'usuarios' 'actualizar' usuario.id %}" class="btn btn-primary btn-sm">Editar</a>
                      <a href="{% url 'usuarios' 'eliminar' usuario.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'core/js/usuarios.js' %}"></script>
<script src="{% static 'core/js/jquery.min.js' %}"></script>
<script src="{% static 'core/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'core/js/dataTables.bootstrap4.min.js' %}"></script>
<script>
  $(document).ready(function() {
    $('#tabla-principal').DataTable();
  });

  // Previsualizar imagen seleccionada
  $(document).ready(function() {
    $('#id_imagen').change(function(evt) {
      const file = evt.target.files[0];
      const reader = new FileReader();
      reader.onload = function(e) {
        $('#cuadro-imagen').attr('src', e.target.result);
      };
      reader.readAsDataURL(file);
    });
  });
</script>
<script src="{% static 'core/css/nosotros.css' %}"></script>
<link rel="stylesheet" href="{% static 'core/css/nosotros.css' %}">
<script src="{% static 'core/js/usuarios.js' %}"></script>
{% endblock script %}